services:
  app:
    build:
      context: ./server # Path to your server Dockerfile
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongodb:27017/bookstoredb
      PORT: 3000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app # Mount for live changes in dev, remove or adjust for prod
      - /app/node_modules # Anonymous volume to avoid host node_modules conflict
    command: sh -c "npm install && npm run dev" # For dev environment to use nodemon
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
